FROM python:3.11-slim-bookworm

# Instala dependências do sistema + curl para o healthcheck
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    libgomp1 \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copia o arquivo de dependências
COPY app/requirements.txt .

# Instala as dependências Python
RUN pip install --no-cache-dir -r requirements.txt

# Copia o código da aplicação
COPY app/ .

EXPOSE 8000

# Executa o Uvicorn
CMD [ "uvicorn", "main:app","--host","0.0.0.0","--port","8000","--workers","2"]
